version: '3.8'  # Indique la version de Docker Compose

networks:
  serving_prod_net:  # Récupère le réseau précédemment défini pour l’API
    external: true

services:
  webapp:
    container_name: webapp  # Crée le service webapp
    build:
      context: .  # Indique le contexte actuel comme emplacement pour le build
      dockerfile: Dockerfile  # Indique l’emplacement du Dockerfile
    ports:
      - "8081:8081"  # Lie le port 8081 du conteneur au port 8081 de votre machine
    networks:
      - serving_prod_net  # Connecte l’application web au réseau de l’API de serving
